trigger:
  branches:
    exclude:
      - "*"

pr:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  # Java version to use
  JAVA_HOME: '/usr/lib/jvm/java-17-openjdk-amd64'
  MAVEN_OPTS: '-Xmx1024m'

steps:
  # Step 1: Checkout the code
  - task: Checkout@1
    displayName: 'Checkout Code'

  # Step 2: Set up Java
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '17'
      jdkArchitecture: 'x64'
    displayName: 'Set up Java 17'

  # Step 3: Cache Maven dependencies
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: |
        maven | "$(Agent.OS)"
      path: ~/.m2/repository
    displayName: 'Cache Maven Dependencies'

  # Step 4: Build the project
  - script: |
      mvn clean install
    displayName: 'Build Project'

  # Step 5: Run unit tests
  - script: |
      mvn test
    displayName: 'Run Unit Tests'

  # Step 6: Publish test results
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/surefire-reports/*.xml'
      testRunTitle: 'Unit Test Results'
    displayName: 'Publish Test Results'